[package]
name = "BlueHash"
description = "A highly secure alternative to existing custom digest algorithms"
authors = ["blueokanna@gmail.com"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"


[dependencies]
rand = "0.8.5"
criterion = { version = "0.5.1", features = ["plotters"] }


[[bench]]
name ="bluebench"
harness = false